window.BIST100_CODES = [
  "AEFES","AGHOL","AKBNK","AKSA","AKSEN","ALARK","ALTNY","ANSGR","ARCLK","ASTOR",
  "BALSU","BIMAS","BRSAN","BRYAT","BSOKE","BTCIM","CANTE","CCOLA","CIMSA","CWENE",
  "DAPGM","DOAS","DOHOL","DSTKF","ECILC","EFOR","EGEEN","EKGYO","ENERY","ENJSA",
  "ENKAI","EREGL","EUPWR","FENER","FROTO","GARAN","GENIL","GESAN","GLRMK","GRSEL",
  "GRTHO","GSRAY","GUBRF","HALKB","HEKTS","ISCTR","ISMEN","IZENR","KCAER","KCHOL",
  "KLRHO","KONTR","KRDMD","KTLEV","KUYAS","MAGEN","MAVI","MGROS","MIATK","MPARK",
  "OBAMS","ODAS","OTKAR","OYAKC","PASEU","PATEK","PETKM","PGSUS","QUAGR","RALYH",
  "REEDR","SAHOL","SASA","SISE","SKBNK","TABGD","TAVHL","TCELL","THYAO","TKFEN",
  "TOASO","TRALT","TRENJ","TRMET","TSKB","TTKOM","TTRAK","TUKAS","TUPRS","TUREX",
  "TURSG","ULKER","VAKBN","VESTL","YEOTK","YKBNK","ZOREN","ASELS","CVKMD","SOKM"
];

window.BIST100_FALLBACK_SECTORS = {
  AKSA: "CHEM",
  ALARK: "HOLD",
  ALTNY: "MINE",
  ASTOR: "MANU",
  BALSU: "FOOD",
  BRYAT: "HOLD",
  BTCIM: "MANU",
  CANTE: "ENER",
  CWENE: "ENER",
  DAPGM: "REIT",
  DSTKF: "HOLD",
  EFOR: "FOOD",
  EGEEN: "MANU",
  GENIL: "HLTH",
  GESAN: "ENER",
  GLRMK: "MANU",
  GRSEL: "TRAN",
  GRTHO: "HOLD",
  ISMEN: "BANK",
  IZENR: "ENER",
  KCAER: "MANU",
  KLRHO: "HOLD",
  KTLEV: "BANK",
  KUYAS: "HOLD",
  MIATK: "TECH",
  OBAMS: "FOOD",
  PASEU: "TRAN",
  PATEK: "TECH",
  QUAGR: "MANU",
  RALYH: "HOLD",
  REEDR: "TECH",
  SASA: "CHEM",
  TABGD: "RETL",
  TRALT: "MINE",
  TRENJ: "TRAN",
  TRMET: "MINE",
  TUREX: "TRAN",
  YEOTK: "ENER",
  ASELS: "MANU",
  CVKMD: "MINE",
  SOKM: "RETL"
};

window.BIST100_FALLBACK_NAMES = {
  AKSA: "Aksa Akrilik",
  ALARK: "Alarko Holding",
  ALTNY: "Altınay Savunma",
  ASTOR: "Astor Enerji",
  BALSU: "Balsu Gıda",
  BRYAT: "Borusan Yat. Paz.",
  BTCIM: "Batıçim",
  CANTE: "Çan2 Termik",
  CWENE: "CW Enerji",
  DAPGM: "DAP Gayrimenkul",
  DSTKF: "Destek Finans",
  EFOR: "Efor Çay",
  EGEEN: "Ege Endüstri",
  GENIL: "Gen İlaç",
  GESAN: "Girişim Elektrik",
  GLRMK: "Gülermak",
  GRSEL: "Gür-Sel Turizm",
  GRTHO: "Grainturk Holding",
  ISMEN: "İş Yatırım Menkul",
  IZENR: "İzdemir Enerji",
  KCAER: "Kocaer Çelik",
  KLRHO: "Kiler Holding",
  KTLEV: "Katılımevim",
  KUYAS: "Kuyumcukent GYO",
  MIATK: "Mia Teknoloji",
  OBAMS: "Oba Makarnacılık",
  PASEU: "Pasifik Eurasia Lojistik",
  PATEK: "Pasifik Teknoloji",
  QUAGR: "Qua Granite",
  RALYH: "Ral Yatırım Holding",
  REEDR: "Reeder Teknoloji",
  SASA: "Sasa Polyester",
  TABGD: "Tab Gıda",
  TRALT: "Tureks Turunç Madencilik",
  TRENJ: "Tren Teknoloji",
  TRMET: "Trend Gayrimenkul Yatırım",
  TUREX: "Tureks Turizm",
  YEOTK: "Yeo Teknoloji",
  ASELS: "Aselsan",
  CVKMD: "CVK Maden",
  SOKM: "Şok Marketler"
};
